image: "https://lh4.googleusercontent.com/fnHp12uomRYkXg6aY1m7OE-AjMpJ-0LNEkj87w5KTOr6oeLQn1S-JOKigl1HiFXtkTVZ6TkQZTNUiwNNdy1T8D6IJ9uRklbTqOQJVsz0WClVF_XZ2hVWWlTgW_ahP3rjOw=w1280"

stages:
  - build
  - test

buildTS3MusicBot:
  stage: build
  script:
    - gradle assemble

runTests:
  stage: test
  script:
    - gradle test

